spring:
  application:
    name: wemeet-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wemeetdb?createDatabaseIfNotExist=true
    username: root
    password: password
    type: org.springframework.jdbc.datasource.SimpleDriverDataSource

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: MYSQL
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      hibernate.dialect.format_sql: true
      hibernate.boot.allow_jdbc_metadata_access: false
      hibernate.jdbc.batch_size: 20
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_structured_entries: false
      hibernate.cache.use_minimal_puts: false
      hibernate.show_sql: true
    hibernate:
      ddl-auto: none

logging:
  level:
    root: info
    org.hibernate.orm.jdbc.bind: trace