version: '3.8'

services:
  mysql:
    image: mysql:8.4.2
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: 'wemeet-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: